const state = { orders: [], products: [], parts: [], company: 'all', query: '', companyQuery: '', status: 'all', sort: 'due-desc' };
const $ = selector => document.querySelector(selector);
const text = value => value === null || value === undefined || value === '' ? '—' : String(value);
const money = value => Number(value || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const date = value => { if (!value) return null; const parsed = new Date(typeof value === 'object' ? value.DateText : value); return Number.isNaN(parsed.getTime()) ? null : parsed; };
const dateLabel = value => { const parsed = date(value); return parsed ? parsed.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : 'No date'; };
const amount = order => Number(order.OrderTotal || order.OrderSubTotal || 0);
const companyName = order => text(order.CompanyName || order.CompnayName || order.CustomerName || 'Unassigned');
const esc = value => text(value).replace(/[&<>"']/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[character]);

async function fetchResource(endpoint) {
  const records = [];
  for (let page = 1; page <= 100; page += 1) {
    const response = await fetch(`/api/corebridge?endpoint=${endpoint}&page=${page}&pageSize=100`);
    const payload = await response.json();
    if (!response.ok || payload?.error) throw new Error(payload?.error || `CoreBridge returned ${response.status}`);
    const pageRecords = Array.isArray(payload) ? payload : payload?.data || payload?.Records || [];
    records.push(...pageRecords);
    if (pageRecords.length < 100) break;
  }
  return records;
}
function visibleOrders() { const orders = state.orders.filter(order => { const haystack = `${order.OrderId} ${companyName(order)} ${order.OrderDescription || ''} ${order.Status || ''}`.toLowerCase(); return (state.company === 'all' || companyName(order) === state.company) && (state.status === 'all' || text(order.Status) === state.status) && haystack.includes(state.query.toLowerCase()); }); const [field, direction] = state.sort.split('-'); return orders.sort((first, second) => { let firstValue; let secondValue; if (field === 'order') { firstValue = Number(first.OrderId || first.EstimateNumber || 0); secondValue = Number(second.OrderId || second.EstimateNumber || 0); } else { const firstDate = date(field === 'due' ? first.OrderDueDate || first.EstimateProjectedOrderDueDate : first.DateCreated); const secondDate = date(field === 'due' ? second.OrderDueDate || second.EstimateProjectedOrderDueDate : second.DateCreated); firstValue = firstDate ? firstDate.getTime() : direction === 'asc' ? Number.POSITIVE_INFINITY : Number.NEGATIVE_INFINITY; secondValue = secondDate ? secondDate.getTime() : direction === 'asc' ? Number.POSITIVE_INFINITY : Number.NEGATIVE_INFINITY; } return (firstValue - secondValue) * (direction === 'asc' ? 1 : -1); }); }
function renderKpis() { const orders = state.orders; const active = orders.filter(order => !/complete|cancel|void/i.test(text(order.Status))); const overdue = active.filter(order => { const due = date(order.OrderDueDate || order.EstimateProjectedOrderDueDate); return due && due < new Date(); }); $('#kpis').innerHTML = [['Portfolio value', money(orders.reduce((sum, order) => sum + amount(order), 0)), `${orders.length} orders loaded`], ['Active work', active.length, `${orders.length ? Math.round(active.length / orders.length * 100) : 0}% of portfolio`], ['Needs attention', overdue.length, overdue.length ? 'Past due orders' : 'No overdue orders']].map(item => `<article class="kpi"><div class="kpi-label">${item[0]}</div><div class="kpi-value">${item[1]}</div><div class="kpi-note">${item[2]}</div></article>`).join(''); }
function renderCompanies() { const groups = {}; state.orders.forEach(order => { const name = companyName(order); if (!groups[name]) groups[name] = { count:0, value:0 }; groups[name].count++; groups[name].value += amount(order); }); const entries = Object.entries(groups).filter(([name]) => name.toLowerCase().includes(state.companyQuery.toLowerCase())).sort((a,b) => b[1].value-a[1].value); $('#company-count').textContent = entries.length; $('#company-list').innerHTML = `<div class="company ${state.company === 'all' ? 'active' : ''}" data-company="all"><div><div class="company-name">All companies</div><div class="company-meta">${state.orders.length} total orders</div></div><div class="company-value">${money(state.orders.reduce((sum, order) => sum + amount(order), 0))}</div></div>` + entries.map(([name, data]) => `<div class="company ${state.company === name ? 'active' : ''}" data-company="${esc(name)}"><div><div class="company-name">${esc(name)}</div><div class="company-meta">${data.count} order${data.count === 1 ? '' : 's'}</div></div><div class="company-value">${money(data.value)}</div></div>`).join(''); document.querySelectorAll('[data-company]').forEach(item => item.addEventListener('click', () => { state.company = item.dataset.company; $('#orders-title').textContent = state.company === 'all' ? 'All orders' : state.company; renderCompanies(); renderOrders(); })); }
function renderOrders() { const orders = visibleOrders(); $('#match-count').textContent = `${orders.length} of ${state.orders.length} orders`; $('#orders-body').innerHTML = orders.map(order => { const due = date(order.OrderDueDate || order.EstimateProjectedOrderDueDate); const overdue = due && due < new Date() && !/complete|cancel|void/i.test(text(order.Status)); return `<tr data-order-id="${esc(order.OrderId)}"><td><strong>${esc(order.OrderId || order.EstimateNumber || '—')}</strong></td><td>${esc(companyName(order))}</td><td>${esc(order.OrderDescription || 'No description')}</td><td><span class="status-pill">${esc(order.Status || 'Unknown')}</span></td><td class="due ${overdue ? 'overdue' : ''}">${overdue ? 'Overdue · ' : ''}${dateLabel(order.OrderDueDate || order.EstimateProjectedOrderDueDate)}</td><td class="number"><strong>${money(amount(order))}</strong></td></tr>`; }).join(''); document.querySelectorAll('[data-order-id]').forEach(row => row.addEventListener('click', () => openOrder(row.dataset.orderId))); $('#empty').hidden = orders.length > 0; }
function humanizeLabel(label) { return label.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/_/g, ' ').replace(/\s*\/\s*/g, ' / ').replace(/\bId\b/g, 'ID').replace(/\bUrl\b/g, 'URL'); }
function detailItems(label, value, depth = 0) { const readableLabel = humanizeLabel(label); const longText = /description|notes?|text/i.test(label); if (value === null || value === undefined || value === '') return `<div class="detail-item ${depth ? 'nested' : ''}"><div class="detail-label">${esc(readableLabel)}</div><div class="detail-value empty-value">Not provided</div></div>`; if (Array.isArray(value)) { if (!value.length) return `<div class="detail-item ${depth ? 'nested' : ''}"><div class="detail-label">${esc(readableLabel)}</div><div class="detail-value empty-value">None</div></div>`; return value.map((item, index) => detailItems(`${label} ${index + 1}`, item, depth)).join(''); } if (typeof value === 'object') return Object.entries(value).map(([key, nestedValue]) => detailItems(`${label} / ${key}`, nestedValue, depth + 1)).join(''); return `<div class="detail-item ${depth ? 'nested' : ''} ${longText ? 'long-text' : ''}"><div class="detail-label">${esc(readableLabel)}</div><div class="detail-value">${esc(value)}</div></div>`; }
function recordSection(title, record, className = '') { return `<div class="record-section ${className}"><h3>${esc(title)}</h3><div class="record-fields">${Object.entries(record).map(([key, value]) => detailItems(key, value)).join('')}</div></div>`; }
function openOrder(orderId) { const order = state.orders.find(item => String(item.OrderId) === String(orderId)); if (!order) return; const products = state.products.filter(item => String(item.OrderId) === String(orderId)); const parts = state.parts.filter(item => String(item.OrderId) === String(orderId)); $('#modal-title').textContent = `Order ${text(order.OrderId)}`; const related = [...products.map(item => ({ label: `Product ${item.ExOrderProductId}`, value: item })), ...parts.map(item => ({ label: `Part ${item.ExOrderProductPartId}`, value: item }))]; $('#order-detail').innerHTML = recordSection('Order information', order) + (related.length ? `<div class="related-heading"><div class="detail-section-title">Related products and parts</div><span>${related.length} records</span></div>${related.map(item => recordSection(item.label, item.value, 'related-record')).join('')}` : ''); $('#order-modal').hidden = false; document.body.style.overflow = 'hidden'; }
function closeOrder() { $('#order-modal').hidden = true; document.body.style.overflow = ''; }
function renderStatuses() { const statuses = [...new Set(state.orders.map(order => text(order.Status)))].sort(); $('#status-filter').innerHTML = '<option value="all">All statuses</option>' + statuses.map(status => `<option value="${esc(status)}">${esc(status)}</option>`).join(''); }
async function load() { $('#refresh').disabled = true; $('#status-text').textContent = 'Syncing'; $('#status-dot').classList.remove('live'); try { [state.orders, state.products, state.parts] = await Promise.all([fetchResource('ExOrder'), fetchResource('ExOrderProduct'), fetchResource('ExOrderProductPart')]); renderKpis(); renderStatuses(); renderCompanies(); renderOrders(); $('#updated').textContent = `Updated ${new Date().toLocaleTimeString([], { hour:'numeric', minute:'2-digit' })} · ${state.products.length} products · ${state.parts.length} parts`; $('#status-text').textContent = 'Live'; $('#status-dot').classList.add('live'); $('#error').hidden = true; } catch (error) { $('#status-text').textContent = 'Unavailable'; $('#error').textContent = error.message; $('#error').hidden = false; } finally { $('#refresh').disabled = false; } }
$('#refresh').addEventListener('click', load); $('#order-search').addEventListener('input', event => { state.query = event.target.value; renderOrders(); }); $('#company-search').addEventListener('input', event => { state.companyQuery = event.target.value; renderCompanies(); }); $('#status-filter').addEventListener('change', event => { state.status = event.target.value; renderOrders(); }); $('#sort-filter').addEventListener('change', event => { state.sort = event.target.value; renderOrders(); }); $('#clear-filters').addEventListener('click', () => { state.company = 'all'; state.query = ''; state.companyQuery = ''; state.status = 'all'; state.sort = 'due-desc'; $('#order-search').value = ''; $('#company-search').value = ''; $('#status-filter').value = 'all'; $('#sort-filter').value = 'due-desc'; $('#orders-title').textContent = 'All orders'; renderCompanies(); renderOrders(); }); document.querySelectorAll('[data-close-modal]').forEach(element => element.addEventListener('click', closeOrder)); document.addEventListener('keydown', event => { if (event.key === 'Escape') closeOrder(); }); load();